dubbo:
  application:
    name: stu_service
  registry:
    address: zookeeper://122.152.200.23:2181
  #默认占用20880端口，加此属性会在20880端口被占用时自动匹配端口
  protocol:
    port: -1
  #消费者不会检查提供者是否存在
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
